name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Tous les jours à minuit
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ZieTech-dev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
